# Generated by Django 4.0.3 on 2022-04-07 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_students'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Students',
            new_name='Student',
        ),
    ]
