# Generated by Django 4.0.3 on 2022-04-08 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_student_name_alter_teacher_name_studentpoint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
